[package]
name = "robotpilot"
version = "0.1.0"
authors = ["Albert Ragány-Németh <me@alb1.hu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
